### ISSUE TITLE
Missing parentheses in if statement in nvd3 submodule causing error

### ISSUE THREAD

**Issue by jordanglassman** [adjust/nvd3-rails#5]
It looks like this commit https://github.com/adeven/nvd3/commit/1f76c023fab2256260596c1ac526e45cd9bee6c0#src/models/scatter.js was cut and pasted from coffeescript or is using one of those exotic JS parsers that doesn't follow ECMA standards (http://forums.udacity.com/questions/7004371/javascript-syntax-no-parentheses-in-an-if-statement).  

This now gives a `Uncaught SyntaxError: Unexpected identifier` error at line 98.

**Comment by jordanglassman** [comment]
I was completely wrong about what was going on here.  Please disregard.  The gem works fine.

**Comment by niiamon** [comment]
Hey @jordanglassman what did you figure the problem to be? I can confirm that line 98 in scatter.js is a problem for me too. The line in question is:

if x.domain()[0]

If I put parentheses around it like this if (x.domain()[0]), it throws another issue:

Unexpected token: name (x) (line: 18232, col: 10, pos: 634109)

How did you fix it?

**Comment by niiamon** [comment]
It seems to be some kind of encoding problem. I am in a bit of a hurry now so I used files I had from another project and without any changes to the files everything works fine.

**Comment by jordanglassman** [comment]
@niiamon now I'm very confused.  I couldn't get this to work, so I tried using the JS files directly from ndv3 (which is actually quite simple).  I then found a typo in my own coffeescript code; I then switched back to the gem and everything worked fine!  I'm looking at a line chart right now, made using the gem.

It seems a highly unlikely coincidence that we both saw the exact same lexical error due to different bugs in our own code.

**Comment by niiamon** [comment]
Yeah that's certainly interesting. I do know that my problems were caused by an encoding problem with the nvd3-rails files I got from this github repo. The files that worked for me were downloaded from the nvd3.org site. I just replaced the vendor/assets with those files and then left the other files that this gem added in place.
